### PR TITLE
add gapbuffer pkg

### PR DESCRIPTION
**Pull request by MorganPeterson**
Gapbuffer
https://github.com/MorganPeterson/gapbuffer

Gapbuffer is a module that allows a developer to add gap buffer data structure for editing strings to their project. It is pure Janet with a simple 7 function interface.

### CODE REVIEW

**Comment by sogaiu** [comment]
@MorganPeterson Very interesting!

Not sure if you've seen but @saikyun's [freja](https://github.com/Saikyun/freja) uses a [gap buffer](https://github.com/saikyun/freja/blob/18c921ca36dec6ae4d5e42ca77471ce33c964a82/freja/new_gap_buffer.janet) too.

**Comment by MorganPeterson** [comment]
@sogaiu I didn't see that. Thanks for pointing it out. I will take a look at it.

My pkg was born of necessity from another project I am working on. As that gets closer to finishing I will be adding more functionality, so, it is good to see there are some ideas in freja to check out.

**Comment by sogaiu** [comment]
@MorganPeterson Was looking over the README and was a little confused about some of the instances of "left" and "right" in the descriptions.

Specifically, the prose (not the names) for `insert-char`, `delete-left`, and `delete-right`.

Are they all as intended?

**Comment by pepe** [comment]
I would also implement the testing flag as a dynamic variable.

**Pull request merged**
