### PR TITLE
Update Contributing.md to be less pedantic

### PR DESCRIPTION
**Pull request by yumaikas**

### CODE REVIEW

**Comment by sogaiu** [comment]
It looks like one of the changes is removing examples.  I think usually it's better to have concrete examples and in this case I don't think it's an improvement to remove them all.

**Comment by yumaikas** [comment]
Closing this PR, as it seems to not be well-thought-out enough, but overall, I think that the list of "bad" names is overbroad, cares more than I do about capitalization. But, I'm also not experienced as a package maintainer

**Comment by sogaiu** [comment]
May be it makes sense to create a discussion about the naming.

**Comment by yumaikas** [comment]
https://github.com/janet-lang/pkgs/issues/29 for anyone who's interested

**Pull request closed without merging**
