### PR TITLE
add judge, a simple test framework

### PR DESCRIPTION
**Pull request by ianthehenry**
It's a bit different from existing test libraries. Inspired by Jane Street's `expect-test` library, although it does not currently support stdout capture.

### CODE REVIEW

**Comment by sogaiu** [comment]
@ianthehenry Neat!  Had not heard of "self-modifying tests" before.

On a side note, perhaps you've seen it already, but may be you'd be interested in another testing thing called [`judge-gen`](https://github.com/sogaiu/judge-gen).

**Comment by pepe** [comment]
@ianthehenry, thank you for the entry, I will look closer at the package later, but I guess it is OK. +1 for the Good Place back story :-).

@sogaiu I wanted to ping you, glad to see you have already seen it.

**Review by pepe — APPROVED** [review]
LGTM

**Comment by ianthehenry** [comment]
Oh no! I didn't realize there was already a project named after the judge. @sogaiu I'm happy to rename this -- I looked at the package listing before I named it, but I didn't know how else to find Janet packages. I probably should've asked in the chat. Anyway you have a much better claim to the name, so if you want to claim it in the package listing I will rename to `expect-tests` or something. (I'm sure no one but me is using it, so I doubt anyone will notice.)

**Comment by sogaiu** [comment]
@ianthehenry It's generous of you to offer to rename, but I don't think it's necesssary :)

On a side note, @goto-engineering, @yumaikas and others are working on [Powered by Janet](https://goto-engineering.github.io/powered-by-janet/) where a fair number of Janet bits can be searched for.

**Pull request merged**
