### PR TITLE
Add repl to pkgs.janet

### PR DESCRIPTION
**Pull request by crocket**

### CODE REVIEW

**Comment by pepe** [comment]
Just one nitpick, isn't the name too generic? Shouldn't it be repltools or something similar? It could be confusing for new users.

**Comment by crocket** [comment]
Any better name than repltools?

**Comment by pepe** [comment]
Well, I have problem naming even my things :-).

**Comment by crocket** [comment]
I think `repl` is fine.

**Comment by pepe** [comment]
I beg to differ there, but no hard feelings :-). And indeed I do not know what are your plans with this lib. 

It is just a confusing name to me. How is it reading, evaluating or printing something in the loop? And it will mislead google searches and so on :-).

I would name it more akin to modules/bindings. But again I do not want to sound harsh or anything, just my 2 (choose your illusional currency).

**Comment by crocket** [comment]
Okay. time to rename it.

**Pull request closed without merging**
